on:
  push:
    tags: [v*]

jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [win-x64, win-x86, win-arm64]
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10
        dotnet-quality: ga
    - name: .NET Publish
      working-directory: PrintDmpStack
      run: dotnet publish -c release -r ${{ matrix.rid }}
    - uses: actions/upload-artifact@v4
      with:
        name: binaries_${{ matrix.rid }}
        path: artifacts/publish/PrintDmpStack/release_${{ matrix.rid }}

  release:
    runs-on: ubuntu-slim
    needs: [build]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v5
    - name: Create or update Release for tag
      run: |
        RELEASE_VERSION="$(echo ${GITHUB_REF_NAME} | cut -f1 -d-)"
        OLD_TAG=$(gh release ls --json name,tagName | jq -r ".[] | select(.name == \"${RELEASE_VERSION}\") | .tagName")
        if [ -n "$OLD_TAG" ]; then
          gh release edit ${OLD_TAG} --tag ${GITHUB_REF_NAME}
        else
          gh release create ${GITHUB_REF_NAME} \
            --title ${RELEASE_VERSION} \
            --generate-notes \
            --draft \
        fi
    - uses: actions/download-artifact@v5
    - name: Upload artifacts to release
      run: |
        ls -R
